[package]
name = "nd-image-converter"
version = "0.3.0"
description = "Fast offline batch image converter"
authors = ["duongtruongdp"]
edition = "2021"

[lib]
name = "nd_image_converter_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
rayon = "1.10"
tokio = { version = "1", features = ["sync"] }
webp = "0.3"
base64 = "0.22"

image = { version = "0.25", features = [
    "jpeg", 
    "png", 
    "webp", 
    "bmp", 
    "ico", 
    "tiff", 
    "tga", 
    "gif", 
    "exr", 
    "pnm", 
    "qoi",
    "avif"
] }

resvg = "0.45"
usvg = "0.45"
rawloader = "0.37"

[build-dependencies]
tauri-build = { version = "2", features = [] }
