import { useEffect, useState } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { getCurrentWebview } from '@tauri-apps/api/webview';
import { open } from '@tauri-apps/plugin-dialog';
import { ArrowRightLeft, ChevronDown, FolderOpen, Loader2 } from 'lucide-react';

type VideoInfo = { path: string; duration: number; width: number; height: number; codec: string };
const formats = ['mp4', 'mov', 'mkv', 'webm'];
const videoExtensions = /\.(mp4|mov|mkv|webm|avi|m4v)$/i;

export const VideoConverterTab = () => {
  const [video, setVideo] = useState<VideoInfo | null>(null); const [outputFormat, setOutputFormat] = useState('webm'); const [videoCodec, setVideoCodec] = useState('vp9'); const [quality, setQuality] = useState(80); const [audio, setAudio] = useState(true); const [outputDirectory, setOutputDirectory] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [openMenu, setOpenMenu] = useState<'format' | 'codec' | null>(null);
  const loadVideo = async (path: string) => { try { setVideo(await invoke<VideoInfo>('probe_video', { path })); setMessage(''); } catch (error) { setMessage(String(error)); } };
  useEffect(() => { const promise = getCurrentWebview().onDragDropEvent((event) => { if (event.payload.type === 'drop') { const path = event.payload.paths.find((item) => videoExtensions.test(item)); if (path) void loadVideo(path); } }); return () => { promise.then((unlisten) => unlisten()); }; }, []);
  const choose = async () => { const selected = await open({ multiple: false, filters: [{ name: 'Video', extensions: ['mp4', 'mov', 'mkv', 'webm', 'avi', 'm4v'] }] }); if (typeof selected === 'string') await loadVideo(selected); };
  const chooseOutputDirectory = async () => { const selected = await open({ directory: true, multiple: false }); if (typeof selected === 'string') setOutputDirectory(selected); };
  const convert = async () => { if (!video || busy) return; setBusy(true); setMessage(''); try { const output = await invoke<string>('convert_video', { options: { inputPath: video.path, outputFormat, videoCodec, quality, audio, outputDirectory: outputDirectory || null } }); setMessage(`Saved: ${output}`); } catch (error) { setMessage(String(error)); } finally { setBusy(false); } };
  const menu = (kind: 'format' | 'codec', value: string, label: string, options: Array<{ value: string; label: string }>, setValue: (value: string) => void) => <div className="relative"><span className="text-xs text-zinc-400">{label}</span><button type="button" onClick={() => setOpenMenu(openMenu === kind ? null : kind)} className="mt-1 h-10 w-full bg-[#161920] border border-zinc-800/80 hover:border-zinc-700 rounded-xl px-3 text-xs text-zinc-100 flex items-center justify-between transition"><span className="uppercase tracking-wide">{options.find(option => option.value === value)?.label}</span><ChevronDown className={`w-3.5 h-3.5 text-zinc-500 transition-transform ${openMenu === kind ? 'rotate-180' : ''}`} /></button>{openMenu === kind && <div className="absolute z-20 mt-1 w-full rounded-xl border border-zinc-700 bg-[#161920] p-1.5 shadow-2xl">{options.map(option => <button type="button" key={option.value} onClick={() => { setValue(option.value); setOpenMenu(null); }} className={`w-full rounded-lg px-3 py-2 text-left text-xs transition ${option.value === value ? 'bg-blue-600 text-white' : 'text-zinc-300 hover:bg-zinc-800 hover:text-white'}`}>{option.label}</button>)}</div>}</div>;
  return <main className="flex-1 overflow-y-auto p-6 max-w-5xl mx-auto w-full"><div className="bg-[#12141a] border border-zinc-800/80 rounded-3xl p-6 space-y-6"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold flex items-center gap-2"><ArrowRightLeft className="w-4 h-4 text-blue-400" /> Video Converter</h2><p className="text-xs text-zinc-500 mt-1">Convert H.264/H.265 MP4, MOV, MKV and WebM files locally.</p></div><button onClick={choose} className="px-3 py-2 rounded-xl bg-blue-600 text-xs font-medium flex items-center gap-2"><FolderOpen className="w-3.5 h-3.5" /> Choose video</button></div>{video ? <><div className="p-4 rounded-2xl bg-zinc-900 text-xs font-mono text-zinc-300">{video.codec} · {video.width}×{video.height} · {video.path.split('/').pop()}</div><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{menu('format', outputFormat, 'Output format', formats.map(format => ({ value: format, label: format })), setOutputFormat)}{menu('codec', videoCodec, 'Video codec', [{ value: 'h264', label: 'H.264' }, { value: 'h265', label: 'H.265' }, { value: 'vp8', label: 'VP8' }, { value: 'vp9', label: 'VP9' }, { value: 'av1', label: 'AV1' }], setVideoCodec)}<label className="text-xs text-zinc-400">Quality ({quality})<input type="range" min="1" max="100" value={quality} onChange={e => setQuality(Number(e.target.value))} className="mt-3 w-full accent-blue-500" /></label><div className="text-xs text-zinc-400"><span>Output folder</span><button type="button" onClick={chooseOutputDirectory} className="mt-1 w-full h-10 bg-[#161920] border border-zinc-800/80 hover:border-zinc-700 rounded-xl px-3 text-left text-xs text-zinc-300 truncate transition">{outputDirectory || 'Same as input'}</button></div></div><label className="flex items-center gap-2 text-xs text-zinc-300"><input type="checkbox" checked={audio} onChange={e => setAudio(e.target.checked)} /> Preserve audio</label><button onClick={convert} disabled={busy} className="px-4 py-2 rounded-xl bg-blue-600 disabled:bg-zinc-700 text-xs font-semibold flex items-center gap-2">{busy && <Loader2 className="w-3.5 h-3.5 animate-spin" />}{busy ? 'Converting…' : 'Convert video'}</button>{message && <p className={`text-xs ${message.startsWith('Saved:') ? 'text-emerald-400' : 'text-red-400'}`}>{message}</p>}</> : <div onClick={choose} className="h-48 border border-dashed border-zinc-700 rounded-2xl flex items-center justify-center text-xs text-zinc-500 cursor-pointer">Drop a video here or choose a file</div>}</div></main>;
};
